logging:
  level: "DEBUG"
  type: "json"

storage:
  type: "inmemory"
  # db:
  #   endpoint: "localhost:5432"
  #   user: "postgres"
  #   database: "events"
  #   pass: "1234"

http:
  host: "localhost"
  port: "8888"

grpc:
  port: "8889"